# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 05:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('appsd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_type', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('reviews', models.CharField(max_length=100)),
                ('imgname', models.CharField(max_length=100)),
                ('imgpath', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion_type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('lname', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('is_registered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='movies',
            name='genere',
        ),
        migrations.DeleteModel(
            name='Genere',
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
