# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsd', '0002_auto_20170701_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giftmapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsd.Category')),
                ('giftid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsd.Gifts')),
            ],
        ),
    ]
