# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsd', '0003_giftmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifts',
            name='catsid',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gifts',
            name='occid',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='qty',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='reviews',
            field=models.CharField(max_length=20),
        ),
    ]
